# Statistical Software

Since this ebook is being created with Biomedical students in mind, I decided cover *R* and SPSS. Wikipedia[^ch-packages-1] has a comprehensive list of statistical software, which is worth checking out.

[^ch-packages-1]: List of statistical packages: <http://bit.ly/2pNLjqU>

Below, I will show you how to download and install *R*, RStudio, and SPSS. I strongly recommend you to download the application of your choice and follow along.

## Package Download & Installation

In this section, you'll find all you need to get started with **RStudio** and **SPSS**. Both computer packages are available for Windows, Mac, and Linux.

### *R* and RStudio

*R* is an open-source computer package used for statistical data analysis and graphics. RStudio combines several tools in one single computer package, which helps one be more productive when using *R*. Although you can use *R* by itself, the tutorials for this book were developed using RStudio. Thus, to follow along, please download both *R* and RStudio.

**Standalone Version**

-   First, download and install *R* from this link[^ch-packages-2]: <http://bit.ly/3bBLKHO>
-   Then, download and install RStudio from this link: <http://bit.ly/2D8H7EU>

[^ch-packages-2]: RStudio will detect *R* the first time you run it.

To take full advantage of *R*, you will need to install a few *R* packages[^ch-packages-3] as they are required to run most of the statistical analysis and to create graphs.

[^ch-packages-3]: Follow this link to learn how to install packages in *R*: <http://bit.ly/2VlJ4sa>

> YouTube[^ch-packages-4] has several video tutorials showing how to install these applications.

[^ch-packages-4]: Visit this link to watch a video tutorial: <http://bit.ly/2OAnETa>

**RStudio Cloud**

If you don't want to download/install *R* and RStudio, you can use the cloud version of RStudio, provided you have access to the Internet. Simply, follow the link below to create a free account and use RStudio online, without the need to install anything in your computer.

-   <https://rstudio.cloud>

### SPSS

Contrary to *R*, SPSS is not free. However, you can download and use SPSS for 14 days by visiting this link: <http://ibm.co/2brfyu1>.

Hearne Software offers SPSS licenses that last 6, 12, or 24 months. This is specially helpful if you are taking an undergraduate or graduate course and needs access to SPSS for the time the course is being taught. Ensure to ask your instructor which package will be necessary, provided the requirements of the course. They offers *premium*, *standard*, and *base* license packages. Follow this link for more information: <http://bit.ly/2w5JcBs>.

## Datasets

The datasets for this ebook are stored on Github[^ch-packages-5]. If necessary, I will direct you to Github to download datasets when covering the topics for this ebook.

[^ch-packages-5]: Link to Github: <http://bit.ly/2VBL7bR>
